profiles.yml:
bde:
  outputs:
    dev:
      type: postgres
      threads: 4
      host: 34.116.96.122
      port: 5432
      user: postgres
      pass: Yy00981180856
      dbname: postgres
      schema: raw
  target: dev
